name: Sentry Release Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install  # or yarn install if using Yarn

      - name: Build project
        env:
          VITE_SENTRY_JAVASCRIPT_DSN: ${{ secrets.VITE_SENTRY_JAVASCRIPT_DSN }}
          VITE_SENTRY_AUTH_TOKEN: ${{ secrets.VITE_SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_ORG: ${{ secrets.VITE_SENTRY_ORG }}
          VITE_SENTRY_PROJECT: ${{ secrets.VITE_SENTRY_PROJECT }}
        run: npm run build  # or yarn build

      - name: Create Sentry release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.VITE_SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.VITE_SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.VITE_SENTRY_PROJECT }}
        run: |
          npm install -g @sentry/cli