name: Sentry Release Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # specify the Node.js version you're using

      - name: Install dependencies
        run: |
          npm install

      - name: Compile assets
        run: |
          npm run build

      - name: Upload source maps to Sentry
        run: |
          npx @sentry/cli releases files ${{ github.sha }} upload-sourcemaps ./dist --ext .js --ext .map
        env:
          VITE_SENTRY_AUTH_TOKEN: ${{ secrets.VITE_SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_ORG: ${{ secrets.VITE_SENTRY_ORG }}
          VITE_SENTRY_PROJECT: ${{ secrets.VITE_SENTRY_PROJECT }}
          VITE_SENTRY_JAVASCRIPT_DSN: ${{ secrets.VITE_SENTRY_JAVASCRIPT_DSN }}
          VITE_SENTRY_DEV_URL: ${{ secrets.VITE_SENTRY_DEV_URL }}